import 'package:dokan_erp/modules/products/domain/entities/dokan_catalog_product.dart';

const List<DokanCatalogProduct> dokanCatalogBootstrapProducts =
    <DokanCatalogProduct>[
  DokanCatalogProduct(
    name: 'মিনিকেট চাল ১কেজি',
    barcode: '880001',
    category: 'চাল-ডাল',
    emoji: '🌾',
    salePrice: 630,
    purchasePrice: 582,
    stock: 48,
    lowStockThreshold: 5,
    salesCount: 48,
    packInfo: 'প্যাকিং ২ কেজি',
  ),
  DokanCatalogProduct(
    name: 'চিনি ১কেজি',
    barcode: '880002',
    category: 'চাল-ডাল',
    emoji: '🧂',
    salePrice: 120,
    purchasePrice: 98,
    stock: 19,
    lowStockThreshold: 5,
    salesCount: 18,
    packInfo: 'দৈনন্দিন ব্যবহার',
  ),
  DokanCatalogProduct(
    name: 'সয়াবিন তেল ১লি',
    barcode: '880003',
    category: 'তেল-মসলা',
    emoji: '🛢️',
    salePrice: 165,
    purchasePrice: 148,
    stock: 24,
    lowStockThreshold: 5,
    salesCount: 24,
    packInfo: 'পুষ্টি ৫ লিটার',
  ),
  DokanCatalogProduct(
    name: 'লাক্স সাবান ১০০গ্রা',
    barcode: '880004',
    category: 'সাবান',
    emoji: '🧼',
    salePrice: 58,
    purchasePrice: 42,
    stock: 4,
    lowStockThreshold: 5,
    salesCount: 12,
    packInfo: 'ব্যক্তিগত যত্ন',
  ),
  DokanCatalogProduct(
    name: 'কোকা কোলা ২৫০মি',
    barcode: '880005',
    category: 'পানীয়',
    emoji: '🥤',
    salePrice: 35,
    purchasePrice: 28,
    stock: 0,
    lowStockThreshold: 5,
    salesCount: 36,
    packInfo: '৫০০ মিলি.',
  ),
  DokanCatalogProduct(
    name: 'ডাইজেস্টিভ বিস্কুট ২০০গ্রা',
    barcode: '880006',
    category: 'বিস্কুট',
    emoji: '🍪',
    salePrice: 75,
    purchasePrice: 60,
    stock: 16,
    lowStockThreshold: 5,
    salesCount: 20,
    packInfo: 'ক্রিস্পি প্যাক',
  ),
  DokanCatalogProduct(
    name: 'চা কোকো ২৫০ মিলি',
    barcode: '880007',
    category: 'প্যাকেট আইটেম',
    emoji: '🥤',
    salePrice: 100,
    purchasePrice: 84,
    stock: 64,
    lowStockThreshold: 5,
    salesCount: 12,
    packInfo: 'প্যাকেট আইটেম',
  ),
  DokanCatalogProduct(
    name: 'চা কোকো ৫০০ মিলি',
    barcode: '880008',
    category: 'প্যাকেট আইটেম',
    emoji: '🥤',
    salePrice: 120,
    purchasePrice: 98,
    stock: 58,
    lowStockThreshold: 5,
    salesCount: 14,
    packInfo: 'প্যাকেট আইটেম',
  ),
  DokanCatalogProduct(
    name: 'সয়াবিন তেল ১ লিটার',
    barcode: '880009',
    category: 'তেল-মসলা',
    emoji: '🛢️',
    salePrice: 185,
    purchasePrice: 165,
    stock: 15,
    lowStockThreshold: 5,
    salesCount: 28,
    packInfo: '১ লিটার',
  ),
  DokanCatalogProduct(
    name: 'সরিষার তেল ৫০০ মিলি',
    barcode: '880010',
    category: 'তেল-মসলা',
    emoji: '🛢️',
    salePrice: 220,
    purchasePrice: 198,
    stock: 14,
    lowStockThreshold: 5,
    salesCount: 10,
    packInfo: '৫০০ মিলি',
  ),
  DokanCatalogProduct(
    name: 'লবণ ১ কেজি',
    barcode: '880011',
    category: 'দৈনন্দিন',
    emoji: '🧂',
    salePrice: 40,
    purchasePrice: 30,
    stock: 40,
    lowStockThreshold: 5,
    salesCount: 22,
    packInfo: '১ কেজি',
  ),
  DokanCatalogProduct(
    name: 'চিনি ১ কেজি',
    barcode: '880012',
    category: 'দৈনন্দিন',
    emoji: '☕',
    salePrice: 135,
    purchasePrice: 118,
    stock: 29,
    lowStockThreshold: 5,
    salesCount: 18,
    packInfo: '১ কেজি',
  ),
  DokanCatalogProduct(
    name: 'বিস্কুট প্যাকেট',
    barcode: '880013',
    category: 'প্যাকেট আইটেম',
    emoji: '🍪',
    salePrice: 80,
    purchasePrice: 66,
    stock: 51,
    lowStockThreshold: 5,
    salesCount: 16,
    packInfo: 'প্যাকেট',
  ),
];
