// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/login" | "/shop/dashboard" | "/staff/dashboard" | "/super-admin/dashboard" | "/super-admin/login" | "/super-admin/master-data" | "/super-admin/master-data/[slug]" | "/super-admin/master-data/product-category" | "/super-admin/master-data/supplier-data" | "/super-admin/reports" | "/super-admin/reports/purchase-report" | "/super-admin/settings" | "/super-admin/settings/activity-log" | "/super-admin/settings/backup" | "/super-admin/settings/feature-toggle" | "/super-admin/settings/general" | "/super-admin/settings/inventory-rules" | "/super-admin/settings/notifications" | "/super-admin/settings/payment-gateway" | "/super-admin/settings/pin" | "/super-admin/settings/roles-permissions" | "/super-admin/settings/security" | "/super-admin/settings/shop-registration" | "/super-admin/settings/sms-otp" | "/super-admin/settings/subscription" | "/super-admin/settings/subscription-rules" | "/super-admin/settings/tax-vat" | "/super-admin/settings/theme" | "/super-admin/subscriptions" | "/supplier/dashboard"
type AppRouteHandlerRoutes = "/api/auth/login"
type PageRoutes = never
type LayoutRoutes = "/" | "/super-admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/login": {}
  "/login": {}
  "/shop/dashboard": {}
  "/staff/dashboard": {}
  "/super-admin": {}
  "/super-admin/dashboard": {}
  "/super-admin/login": {}
  "/super-admin/master-data": {}
  "/super-admin/master-data/[slug]": { "slug": string; }
  "/super-admin/master-data/product-category": {}
  "/super-admin/master-data/supplier-data": {}
  "/super-admin/reports": {}
  "/super-admin/reports/purchase-report": {}
  "/super-admin/settings": {}
  "/super-admin/settings/activity-log": {}
  "/super-admin/settings/backup": {}
  "/super-admin/settings/feature-toggle": {}
  "/super-admin/settings/general": {}
  "/super-admin/settings/inventory-rules": {}
  "/super-admin/settings/notifications": {}
  "/super-admin/settings/payment-gateway": {}
  "/super-admin/settings/pin": {}
  "/super-admin/settings/roles-permissions": {}
  "/super-admin/settings/security": {}
  "/super-admin/settings/shop-registration": {}
  "/super-admin/settings/sms-otp": {}
  "/super-admin/settings/subscription": {}
  "/super-admin/settings/subscription-rules": {}
  "/super-admin/settings/tax-vat": {}
  "/super-admin/settings/theme": {}
  "/super-admin/subscriptions": {}
  "/supplier/dashboard": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/super-admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
