// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shop/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/shop/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/staff/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/staff/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/master-data/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/master-data/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/master-data/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/master-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/master-data">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/master-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/master-data/product-category/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/master-data/product-category">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/master-data/product-category/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/master-data/supplier-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/master-data/supplier-data">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/master-data/supplier-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/activity-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/activity-log">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/activity-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/backup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/backup">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/backup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/feature-toggle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/feature-toggle">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/feature-toggle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/general">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/inventory-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/inventory-rules">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/inventory-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/payment-gateway/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/payment-gateway">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/payment-gateway/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/pin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/pin">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/pin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/roles-permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/roles-permissions">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/roles-permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/security">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/shop-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/shop-registration">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/shop-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/sms-otp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/sms-otp">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/sms-otp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/subscription-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/subscription-rules">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/subscription-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/tax-vat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/tax-vat">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/tax-vat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/settings/theme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/settings/theme">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/settings/theme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supplier/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplier/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/supplier/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/super-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../src/app/super-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
